language: node_js
sudo: false
node_js:
  - "0.10"
  - "0.12"
before_install:
  - sudo apt-get install -y libxml2-utils
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export BROWSERS=Firefox
  - npm install -g mocha
script: make travis
