#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const transformer = require('enketo-transformer');

const xmlDir = 'test/transformation/xforms';

fs.readdirSync(xmlDir)
  .filter(f => f.endsWith('.xml'))
  .reduce((promiseChain, file) =>
      promiseChain
        .then(() => console.log(`# Processing: ${file}…`))
        .then(() => fs.readFileSync(`${xmlDir}/${file}`, { encoding:'utf8' }))
        .then(xform => transformer.transform({ xform }))
        .then(({ form, model }) => {
          const name = path.parse(file).name;
          fs.writeFileSync(`test/transformation/reference-xml/${name}.html.xml`,  form);
          fs.writeFileSync(`test/transformation/reference-xml/${name}.model.xml`, model);
        })
        .then(() => console.log(`# Done: ${file}`)),
      Promise.resolve())
  .then(() => console.log('Update complete.'));
